### ISSUE TITLE
Some missing objects warning

### ISSUE THREAD

**Issue by knro** [lupinix/kstars-openngc#1] opened 2017-07-11 23:17 UTC
2017-07-12T02:14:30.156 - WARN - "Star HD20794 not found."
2017-07-12T02:14:30.167 - WARN - "Star HD98230 not found."
2017-07-12T02:14:30.179 - DEBG - File opened:  "/usr/share/kstars/ngcic.dat"
2017-07-12T02:14:30.179 - DEBG - Loading NGC/IC objects
2017-07-12T02:14:30.699 - DEBG - File opened:  "/usr/share/kstars/asteroids.dat"
2017-07-12T02:14:30.818 - DEBG - File opened:  "/usr/share/kstars/comets.dat"
2017-07-12T02:14:30.974 - DEBG - Starting the timer
2017-07-12T02:14:30.977 - WARN - "Object named M 102 not found"
2017-07-12T02:14:31.016 - WARN - "Object named M 102 not found"
2017-07-12T02:14:31.061 - WARN - "Object named NGC 4676 not found"
2017-07-12T02:14:31.070 - DEBG - The current Date/Time is:  "Wed Jul 12 02:14:31 2017 GMT+0300"
2017-07-12T02:14:31.070 - DEBG - glibc >= 2.1 detected.  Using GNU extension sincos()
2017-07-12T02:14:31.149 - WARN - "Object named M 102 not found"
2017-07-12T02:14:31.252 - WARN - "Object named M 102 not found"
2017-07-12T02:14:31.273 - WARN - "Object named NGC 61 not found"
2017-07-12T02:14:31.320 - WARN - "Object named NGC 78 not found"
2017-07-12T02:14:31.436 - WARN - "Object named NGC 235 not found"
2017-07-12T02:14:31.500 - WARN - "Object named NGC 526 not found"
2017-07-12T02:14:31.584 - WARN - "Object named NGC 6050A not found"
2017-07-12T02:14:31.731 - WARN - "Object named NGC 3314 not found"
2017-07-12T02:14:31.757 - WARN - "Object named M 102 not found"
2017-07-12T02:14:31.789 - WARN - "Object named NGC 3808 not found"
2017-07-12T02:14:31.881 - WARN - "Object named NGC 4676 not found"
2017-07-12T02:14:32.102 - WARN - "Object named NGC 7318 not found"
2017-07-12T02:14:32.221 - WARN - "Object named Europa not found"

**Comment by lupinix** [comment] 2017-07-12 09:47
Thanks, will check my table and upstream OpenNGC for these objects.

**Comment by lupinix** [comment] 2017-07-12 19:47
@mattiaverga I checked and found that M 102 and the NGC objects are already missing in OpenNGC itself, is there any reason for that?

**Comment by lupinix** [comment] 2017-07-12 20:24
See commit referenced. Maybe these objects are not really missing but only the sub-objects are listed as all missing objects (except M 102) are pairs.

**Comment by mattiaverga** [comment] 2017-07-15 08:06
@lupinix OpenNGC is built upon Nasa Extragalactic Database, which considers M102 to be a duplicate of M101.

About the other objects, I added the missing GPairs in db11510b6f7caf1c86b4337f8a0b4d31a69453ce thanks.

**Comment by lupinix** [comment] 2017-12-15 18:38
Issue fixed for some time now.

**Closed as completed by lupinix** 2017-12-15 18:38 UTC
Labels: bug
